[env:heltec_wifi_lora_32_V3]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200
upload_port = COM6
monitor_port = COM6
lib_deps =
    jgromes/RadioLib @ ^7.1.2
    ThingPulse/ESP8266 and ESP32 OLED driver for SSD1306 displays @ ^4.6.1
    bblanchon/ArduinoJson @ ^7.3.1
