[env:heltec_wifi_lora_32_V3]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200
upload_port = COM7
monitor_port = COM7
lib_deps =
    jgromes/RadioLib @ ^7.1.2
    adafruit/Adafruit BMP280 Library @ ^2.6.8
    adafruit/Adafruit MPU6050 @ ^2.2.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    mikalhart/TinyGPSPlus @ ^1.0.3
    ThingPulse/ESP8266 and ESP32 OLED driver for SSD1306 displays @ ^4.6.1
